
-- Notifications table
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone text NOT NULL,
  order_id bigint NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'general',
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Delivery confirmation codes table
CREATE TABLE public.delivery_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL UNIQUE,
  code text NOT NULL,
  driver_id bigint NOT NULL,
  customer_phone text NOT NULL,
  is_used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + interval '2 hours')
);

-- Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_codes ENABLE ROW LEVEL SECURITY;

-- Notifications RLS: customers can view their own notifications
CREATE POLICY "Customers can view own notifications"
  ON public.notifications FOR SELECT
  USING (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.phone = notifications.customer_phone
    )
  );

-- Customers can update (mark as read) their own notifications
CREATE POLICY "Customers can update own notifications"
  ON public.notifications FOR UPDATE
  USING (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.phone = notifications.customer_phone
    )
  );

-- Drivers can insert notifications
CREATE POLICY "Drivers can insert notifications"
  ON public.notifications FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles p JOIN drivers d ON p.phone = d.phone
      WHERE p.id = auth.uid() AND p.user_type = 'driver'
    )
  );

-- Delivery codes: drivers can insert
CREATE POLICY "Drivers can insert delivery codes"
  ON public.delivery_codes FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles p JOIN drivers d ON p.phone = d.phone
      WHERE p.id = auth.uid() AND p.user_type = 'driver'
    )
  );

-- Drivers can view their own delivery codes
CREATE POLICY "Drivers can view own delivery codes"
  ON public.delivery_codes FOR SELECT
  USING (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles p JOIN drivers d ON p.phone = d.phone
      WHERE p.id = auth.uid() AND p.user_type = 'driver' AND d.id = delivery_codes.driver_id
    )
  );

-- Drivers can update delivery codes (mark as used)
CREATE POLICY "Drivers can update own delivery codes"
  ON public.delivery_codes FOR UPDATE
  USING (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles p JOIN drivers d ON p.phone = d.phone
      WHERE p.id = auth.uid() AND p.user_type = 'driver' AND d.id = delivery_codes.driver_id
    )
  );

-- Customers can view delivery codes for their orders
CREATE POLICY "Customers can view own delivery codes"
  ON public.delivery_codes FOR SELECT
  USING (
    auth.uid() IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.phone = delivery_codes.customer_phone
    )
  );

-- Enable realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
